CREATE TABLE BNEXT_USER (
	id INTEGER NOT NULL PRIMARY KEY,
	name	VARCHAR(100) NOT NULL,
	last_name VARCHAR(200) NOT NULL,
	phone VARCHAR(15) NOT NULL UNIQUE);
	
CREATE SEQUENCE USER_ID_GENERATOR START WITH 1 INCREMENT BY 1;