CREATE TABLE BNEXT_USER_CONTACT (
	id INTEGER NOT NULL PRIMARY KEY,
	contact_name VARCHAR(100) NOT NULL,
	phone VARCHAR(15) NOT NULL);
	
CREATE SEQUENCE USER_CONTACT_ID_GENERATOR START WITH 1 INCREMENT BY 1;